import { initReactI18next } from "react-i18next";
import i18next from "i18next";

i18next.use(initReactI18next).init({
  fallbackLng: "en",
  fallbackNS: "common",
  resources: {
    en: {
      translation: {
        welcome: "welcome to my shopping cart",
        signup: "sign up",
        signin: "sign in",
        upload : 'upload',
        products: "products",
        pay: "pay",
        total: "total",
        logout: "logout",
        add: "add",
        added: "added",
        notfound: "user not found",
        users: "users",
        payment: "payment",
        deleteproducts: "delete products",
        addproduct: "add products",
        updateprice: "update price",
        users: "users",
        delete: "delete",
        update: "update",
        all: "all",
        fruits: "fruits",
        dairy: "dairy",
        juices: "juices",
        bread: "bread",
        salt : 'salt',
        meat: "meat",
        can: "can",
        other: "other",
        hello: "hello",
        low_to_high: "low to high",
        high_to_low: "high to low",
        sort_price: "sort by price",
        drinks: "drinks",
        apple: "apple",
        tuna: "tuna",
        fish: "fish",
        sweetcorn: "sweet corn",
        oliveoil: "olive oil",
        ribs: "ribs",
        milk: "milk",
        water: "water",
        bread: "bread",
        watermelon: "watermelon",
        eggs: "eggs",
        sugar: "sugar",
        cheese: "cheese",
        chocolatemilk: "chocolatemilk",
        frenchfries : 'french fries'
      },
    },
    he: {
      translation: {
        welcome: "ברוכים הבאים לאתר הקניות",
        signup: "הרשמה",
        signin: "התחברות",
        upload : 'העלאה',
        products: "מוצרים",
        pay: "שלם",
        total: "total",
        logout: "יציאה",
        add: "הוספה",
        added: "התווסף",
        notfound: "משתמש לא נמצא",
        users: "משתמשים",
        payment: "תשלום",
        deleteproducts: "מחיקת מוצרים",
        addproduct: "הוספת מוצרים",
        updateprice: "עדכון מחיר",
        users: "משתמשים",
        delete: "מחיקה",
        update: "עדכון",
        all: "הכל",
        fruits: "פירות",
        dairy: "חלב",
        juices: "מיצים",
        meat: "בשר",
        can: "שימורים",
        other: "אחר",
        hello: "שלום",
        sort_price: "מיון לפי מחיר",
        low_to_high: "מנמוך לגבוה",
        high_to_low: "מגבוה לנמוך",
        drinks: "שתייה",
        apple: "תפוח",
        tuna: "טונה",
        fish: "דג",
        salt : 'מלח',
        sweetcorn: "תירס מתוק",
        oliveoil: "שמן זית",
        ribs: "צלעות",
        milk: "חלב",
        water: "מים",
        bread: "לחם",
        watermelon: "אבטיח",
        eggs: "ביצים",
        sugar: "סוכר",
        cheese: "גבינה",
        chocolatemilk: "שוקו",
        frenchfries : "צ'יפס",
      },
    },
  },
});
